version: "3.8"

services:
  minecraft:
    build:
      context: .
    container_name: minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./world:/app/world # Persist world data
      - ./server.properties:/app/server.properties # Server configuration
      - ./eula.txt:/app/eula.txt # Accept the EULA
    environment:
      - EULA=TRUE
